### PR TITLE
Implemented getActiveQuarterList method

### LINKED ISSUE #6: Implement `getActiveQuarterList` method (Backend only)
As a precursor to a future new job that updates all course information for all active quarters at some scheduled interval (e.g. once an hour, once a day, etc.) in this issue you will add a new method to `UCSBAPIQuarterService` called `getActiveQuarterList`  that will return an `ArrayList<String>` value that is a list of the YYYYQ codes starting with the current quarter, and ending with the current value returned by getEndQtrYYYYQ.

You'll also add a endpoint to the `UCSBAPIQuarterController` as follows:

`GET /api/public/activeQuarters` 

the invokes this method and returns the value.

# Details

The `UCSBAPIQuarterService` has these methods:

* `public String getStartQtrYYYYQ()` returns the start quarter for the app in YYYYQ format (i.e. the oldest quarter that is available in the drop down menus in the app).
*  `public String getEndQtrYYYYQ()` returns the start quarter for the app in YYYYQ format (i.e. the newest quarter that is available in the drop down menus in the app, which may be in the future)
* `public String getCurrentQuarterYYYYQ()` gets the current quarter in YYYYQ format.

There is also this method in `models/Quarter.java`

 * `public static List<Quarter> quarterList(String start, String end)` which returns a list of Quarter objects starting at start quarter (specified in YYYYQ format) and ending with end quarter  (specified in YYYYQ format)

Using these tools, and *not* reinventing the wheel, but making as much use of existing methods as possible, add a method to `UCSBAPIQuarterService` called `getActiveQuarterList`  that will return an `ArrayList<String>` value that is a list of the YYYYQ codes starting with the current quarter, and ending with the current value returned by getEndQtrYYYYQ.

For example:

* If the value returned by `getCurrentQuarterYYYYQ` is `20244`  (F24) and the value of END_QTR is `20251` (W25), then the value returned by `getActiveQuarterList` should be `["20244", "20251"]`.
* If the value  returned by `getCurrentQuarterYYYYQ` is `20252`  (S25) and the value of END_QTR is `20254` (F25), then the value returned by `getActiveQuarterList` should be `["20252", "20253", "20254"]`.

# Acceptance Criteria:

- [x] New method implemented as described above
- [x] New controller endpoint implemented as described above

### PR DESCRIPTION
**Pull request by ChristopherChau**
Closes #6

Added a method to return ArrayList<String> to list YYYYQ codes from current quarter and ending with current value returned by getEndQtrYYYYQ. This method is called from the endpoint /api/public/activeQuarters defined in the UCSBAPIQuarterController

Test [here](https://courses-christopherchau.dokku-03.cs.ucsb.edu/)

### CODE REVIEW

**Review by pconrad — APPROVED** [review]
LGTM.  Will want to test on dokku though.

**Comment by ChristopherChau** [comment]
Deployment has been added in the PR

**Review by chloecweng — APPROVED** [review]
LGTM

**Review by raysujf — APPROVED** [review]
LGTM

**Pull request merged**
