### PR TITLE
Detailed log page for long running jobs

### LINKED ISSUE #26: FEATURE: Detailed log page for long running jobs
- Related to #3 
- New page: `/admin/jobs/logs/:id` where `:id` is the name of the long running job. On that page, the entire job log is shown. 
- Next Step: Add button to JobsTable to link to `/admin/jobs/logs/:id`

### PR DESCRIPTION
**Pull request by SameerSRao**
- Closes #26 
- Added `JobsLogTable` component which shows a detailed view for a particular job. Shows the full Job Log
- Added `JobsLogPage` page which displays the `JobsLogTable` for a long running job
- Added route in `App.js` which routes `/admin/jobs/logs/:id` to the `JobsLogPage` for the respective long running job 
- Dokku Deployment: https://courses-sameer.dokku-03.cs.ucsb.edu/

### CODE REVIEW

**Review by ChristopherChau — APPROVED** [review]
LGTM

**Comment by pconrad** [comment]
This PR description claims that it closes #26

image

BUT IT DOES NOT.  It only partially addresses the features requested in PR26, and not in a way that is mergable, because it *removes needed functionality* without replacing it with something suitable.

In particular, the idea is to truncate long job logs and *at the same time* offer an alternative link to see the full job logs.

What that means is that we MUST merge this in a specific order. 
* We must merge a feature that allows the user to see the FULL log on a separate page first (even if we aren't using it yet)
* Only THEN can you add a feature that truncates the log

Plus, you need to signal to the user when the log has been truncated.  That's not happening here.

Please go back to the original issue, read it, and understand the end user needs better. I'm marking this as a draft PR for now, because it's not mergeable until we have a PR that builds the other parts of issue #26

**Comment by SameerSRao** [comment]
> This PR description claims that it closes #26
> image
> 
> BUT IT DOES NOT. It only partially addresses the features requested in PR26, and not in a way that is mergable, because it _removes needed functionality_ without replacing it with something suitable.
> 
> In particular, the idea is to truncate long job logs and _at the same time_ offer an alternative link to see the full job logs.
> 
> What that means is that we MUST merge this in a specific order.
> 
>     * We must merge a feature that allows the user to see the FULL log on a separate page first (even if we aren't using it yet)
> 
>     * Only THEN can you add a feature that truncates the log
> 
> 
> Plus, you need to signal to the user when the log has been truncated. That's not happening here.
> 
> Please go back to the original issue, read it, and understand the end user needs better. I'm marking this as a draft PR for now, because it's not mergeable until we have a PR that builds the other parts of issue #26

#31 adds a button to the main jobs table that links to the detailed log page added in this issue.

**Comment by pconrad** [comment]
Please deploy THIS branch to dokku, not one from two days ago.

**Review by pconrad — APPROVED** [review]
LGTM.  I'd prefer if the Navigate were not inside the stryker exception, but we'll fight that battle another day.

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
